### PR TITLE
dev-python/snakemake: Update Manifest

### PR DESCRIPTION
**Pull request by mschilli87**
Trying to `emerge dev-python/snakemake` failed fetching the distfile from
a mirror and fell back to fetching it from [GitHub](https:/github.com//snakemake/snakemake/archive/v5.31.1.tar.gz).
However, the checksum failed against the Manifest ([likely because they
changed](https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745) when re-generating the tarball on their side).

This PR updates the Manifest with the current checksums.

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
Thank you for your PR,

This commit is not signed-off, which means that according to Gentoo's copyright policy I cannot merge this :( https://www.gentoo.org/glep/glep-0076.html

(Also, we use thin-manifests in this repository, which means that the manifest file should only contain hashes of the distfiles and not of the ebuild itself, if you use `repoman ci` for committing instead of `git commit` it will take care of this automatically for you)

However, I did just version bump this package, which should have fixed the fetching issue as well (at least it is working for me now). Let me know if there are still any issues :smile:

**Comment by mschilli87** [comment]
Dear @AndrewAmmerlaan,

Git would easily allow you to amend the commit to your liking and merge it then.
If you prefer people to not contribute working solutions to broken packages, that's fine with me.
I'll simply stop using this Overlay and rather maintain the few ebuilds I need in a local overlay without giving back to the community.

Note that I don't mind being pointed to contribution guidelines but I encountered a problem and instead of opening an issue I tracked it down, fixed it, tested it locally, and shared my fix. All that was left for the maintainers was deleting two lines that do not do any harm and changing the commit messages. It's not that there is any copyright issue here with my contribution. Nobody would claim intelectual property of a changed hash.

I just wanted to let you know how discouraging I found this attempt of contributing to the project.

**Comment by mschilli87** [comment]
PS: I unmasked the new version added yesterday (`=dev-python/snakemake-5.31.1 ~amd64`)
and ran into the exact same problem again:

```
>>> Downloading 'ftp://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/distfiles/layout.conf'
--2021-02-13 14:21:13--  ftp://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/distfiles/layout.conf
           => ‘/var/portage/distfiles/.layout.conf.ftp.spline.inf.fu-berlin.de.__download__’
Resolving ftp.spline.inf.fu-berlin.de... 130.133.110.66
Connecting to ftp.spline.inf.fu-berlin.de|130.133.110.66|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /mirrors/gentoo/distfiles ... done.
==> SIZE layout.conf ... 45
==> PASV ... done.    ==> RETR layout.conf ... done.
Length: 45 (unauthoritative)


layout.conf           0%[                    ]       0  --.-KB/s               
layout.conf         100%[===================>]      45  --.-KB/s    in 0s      

2021-02-13 14:21:19 (1.85 MB/s) - ‘/var/portage/distfiles/.layout.conf.ftp.spline.inf.fu-berlin.de.__download__’ saved [45]

>>> Downloading 'ftp://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/distfiles/0a/snakemake-5.32.2.tar.gz'
--2021-02-13 14:21:19--  ftp://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/distfiles/0a/snakemake-5.32.2.tar.gz
           => ‘/var/portage/distfiles/snakemake-5.32.2.tar.gz.__download__’
Resolving ftp.spline.inf.fu-berlin.de... 130.133.110.66
Connecting to ftp.spline.inf.fu-berlin.de|130.133.110.66|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /mirrors/gentoo/distfiles/0a ... done.
==> SIZE snakemake-5.32.2.tar.gz ... done.

==> PASV ... done.    ==> RETR snakemake-5.32.2.tar.gz ... 
No such file ‘snakemake-5.32.2.tar.gz’.

>>> Downloading 'http://distfiles.gentoo.org/distfiles/layout.conf'
--2021-02-13 14:21:25--  http://distfiles.gentoo.org/distfiles/layout.conf
Resolving distfiles.gentoo.org... 185.246.208.17, 2a02:6ea0:ce00::3
Connecting to distfiles.gentoo.org|185.246.208.17|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 45 [text/plain]
Saving to: ‘/var/portage/distfiles/.layout.conf.distfiles.gentoo.org.__download__’


          /var/port   0%[                    ]       0  --.-KB/s               
/var/portage/distfi 100%[===================>]      45  --.-KB/s    in 0s      

2021-02-13 14:21:30 (4.10 MB/s) - ‘/var/portage/distfiles/.layout.conf.distfiles.gentoo.org.__download__’ saved [45/45]

>>> Downloading 'http://distfiles.gentoo.org/distfiles/0a/snakemake-5.32.2.tar.gz'
--2021-02-13 14:21:30--  http://distfiles.gentoo.org/distfiles/0a/snakemake-5.32.2.tar.gz
Resolving distfiles.gentoo.org... 185.246.208.17, 2a02:6ea0:ce00::3
Connecting to distfiles.gentoo.org|185.246.208.17|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-13 14:21:36 ERROR 404: Not Found.

>>> Downloading 'http://ibiblio.org/pub/Linux/distributions/gentoo/distfiles/layout.conf'
--2021-02-13 14:21:36--  http://ibiblio.org/pub/Linux/distributions/gentoo/distfiles/layout.conf
Resolving ibiblio.org... 152.19.134.40, 2610:28:3090:3000:0:bad:cafe:23
Connecting to ibiblio.org|152.19.134.40|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-13 14:21:41 ERROR 404: Not Found.

!!! Couldn't download '.layout.conf.ibiblio.org'. Aborting.
>>> Downloading 'http://ibiblio.org/pub/Linux/distributions/gentoo/distfiles/snakemake-5.32.2.tar.gz'
--2021-02-13 14:21:41--  http://ibiblio.org/pub/Linux/distributions/gentoo/distfiles/snakemake-5.32.2.tar.gz
Resolving ibiblio.org... 152.19.134.40, 2610:28:3090:3000:0:bad:cafe:23
Connecting to ibiblio.org|152.19.134.40|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-13 14:21:46 ERROR 404: Not Found.

>>> Downloading 'https://github.com/snakemake/snakemake/archive/v5.32.2.tar.gz'
--2021-02-13 14:21:46--  https://github.com/snakemake/snakemake/archive/v5.32.2.tar.gz
Resolving github.com... 140.82.121.4
Connecting to github.com|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/snakemake/snakemake/tar.gz/v5.32.2 [following]
--2021-02-13 14:21:52--  https://codeload.github.com/snakemake/snakemake/tar.gz/v5.32.2
Resolving codeload.github.com... 140.82.121.10
Connecting to codeload.github.com|140.82.121.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/var/portage/distfiles/snakemake-5.32.2.tar.gz.__download__’


          /var/port     [<=>                 ]       0  --.-KB/s               
         /var/porta     [ <=>                ] 325.31K  1.59MB/s               
        /var/portag     [  <=>               ] 711.56K  1.74MB/s               
       /var/portage     [   <=>              ]   1.04M  1.59MB/s               
      /var/portage/     [    <=>             ]   1.50M  1.72MB/s               
     /var/portage/d     [     <=>            ]   1.99M  1.86MB/s               
    /var/portage/di     [      <=>           ]   2.41M  1.90MB/s               
   /var/portage/dis     [       <=>          ]   2.89M  1.93MB/s               
  /var/portage/dist     [        <=>         ]   3.29M  1.94MB/s               
 /var/portage/distf     [         <=>        ]   3.83M  2.02MB/s               
/var/portage/distfi     [          <=>       ]   4.26M  2.03MB/s               
var/portage/distfil     [           <=>      ]   4.74M  2.06MB/s               
ar/portage/distfile     [            <=>     ]   5.17M  2.07MB/s               
r/portage/distfiles     [             <=>    ]   5.60M  2.07MB/s               
/portage/distfiles/     [              <=>   ]   6.06M  2.09MB/s               
portage/distfiles/s     [               <=>  ]   6.53M  2.11MB/s               
/var/portage/distfi     [                <=> ]   6.69M  2.11MB/s    in 3.2s    

2021-02-13 14:21:55 (2.11 MB/s) - ‘/var/portage/distfiles/snakemake-5.32.2.tar.gz.__download__’ saved [7010842]

!!! Fetched file: snakemake-5.32.2.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      7010842
!!! Expected: 7010849
Refetching... File renamed to '/var/portage/distfiles/snakemake-5.32.2.tar.gz._checksum_failure_.ral45_q_'

!!! Couldn't download 'snakemake-5.32.2.tar.gz'. Aborting.
[31;01m * [39;49;00mFetch failed for 'dev-python/snakemake-5.32.2', Log file:
[31;01m * [39;49;00m '/var/tmp/portage/dev-python/snakemake-5.32.2/temp/build.log'
```

Due to my previous experience, I don't feel like investing any of my time into resolving this anymore.

Looks like it is time to

```ssh
sudo eselect disable science
```

;-)

**Comment by AndrewAmmerlaan** [comment]
> If you prefer people to not contribute working solutions to broken packages, that's fine with me.

Not at all, I very much appreciate that you went through the trouble of tracking down the problem.

>  All that was left for the maintainers was deleting two lines that do not do any harm and changing the commit messages. It's not that there is any copyright issue here with my contribution. Nobody would claim intelectual property of a changed hash.

However, I cannot sign-off a commit for someone else. it is not that I don't _want_ to, I actually _cannot_ do this, If I would the git hooks will reject my push. And I also cannot sign-off a commit with my own name that is authored by someone else, again the git hooks would complain and reject my push.

To me the problem seemed trivial to fix, therefore I opted to just `repoman manifest` it myself, instead of bothering you with having to `git rebase` the whole PR to comply with the Gentoo copyright policy. I only meant to save you time, and fix this quickly. No disrespect to you, your PR, or your efforts was intended, and I am genuinely sorry that I have made you feel this way.

**Comment by mschilli87** [comment]
Not a big deal really. I guess I was a bit dramatic in my previous reply. Of course I meant for you to amend the commit changing the author to yourself, signing of, if you really wanted to giving me a co-author credit as per the commit message, force pushing to my branch and merging the PR, instead of closing it for basically bureaucratic reasons.

Bottom line, this is my experience:

1. It does not work.
2. I add it to my local overlay, test again, same error is reproducible.
3. I build a new manifest (which added checksums for the non-distfiles as well).
4. I test and it works.
5. I fork this repo, copy over the Manifest file from my local overlay, write a commit message that explains why this change is needed, push to a new branch of my fork and open a PR.
6. I take the time to format the PR and add links where appropriate to make review as easy as possible.
7. My PR gets closed for policy reasons that concern copyright. Even though IANAL, I am pretty sure nothing in this commit would qualify for copyright at all. But I am promised a fix forcing me to either keep maintaining my own ebuild or upgrading to yet another newer version.
8. I take the time to do the update so I can get rid of my local ebuild.
9. I get the exact same error as yesterday.

**Comment by AndrewAmmerlaan** [comment]
I understand that when the PR is all of a sudden marked as "Closed" that this might feel like it has been discarded or ignored. However, I would like to add that a PR that is merged is still marked as "Closed" in Gentoo repositories. This is because we don't actually use GitHub directly, we push to this instead: https://gitweb.gentoo.org/ which is then mirrored to GitHub. To merge PRs we use this utility named PRam. So as an example, if I were to merge a PR I would: `pram -r gentoo/sci 1052` followed by `git push`. PRam will add `Closes: https://github.com/gentoo/sci/pull/1052` to the commit message, which will trigger the gentoo-bot to automatically close the PR. Note that all PRs that have been processed/resolved are marked as "Closed", regardless of whether they have been merged or not, none of them are marked as "Merged". So when the gentoo-bot marks this PR as "Closed" that does not mean that it has been discarded, rejected or ignored. Though I can understand that this might feel that way.

For this PR the PRam tool fails, because of the missing sign-off:
```
pram -r gentoo/sci 1052
--2021-02-13 18:57:20--  https://github.com/gentoo/sci/pull/1052.patch
Resolving github.com... 140.82.121.3
Connecting to github.com|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://patch-diff.githubusercontent.com/raw/gentoo/sci/pull/1052.patch [following]
--2021-02-13 18:57:20--  https://patch-diff.githubusercontent.com/raw/gentoo/sci/pull/1052.patch
Resolving patch-diff.githubusercontent.com... 140.82.121.4
Connecting to patch-diff.githubusercontent.com|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from patch-diff.githubusercontent.com attempted to set domain to github.com
Length: unspecified [text/plain]
Saving to: ‘/tmp/tmp.CUsC29FwnT/all.patch’

/tmp/tmp.CUsC29FwnT/all.patch            [ <=>                                                                  ]   2.00K  --.-KB/s    in 0s

2021-02-13 18:57:20 (115 MB/s) - ‘/tmp/tmp.CUsC29FwnT/all.patch’ saved [2049]

Commit no. 0001 was not signed off by the author!
```
Now I could of course still download and apply it manually, but unless I change the author to myself and add my own sign-off, `git push` would still reject it with a similar error. Therefore, I might as well just run `repoman manifest` and `repoman ci` myself and create a whole new commit, which is what I did in this case (I added the version bump while I was at it).

> My PR gets closed for policy reasons that concern copyright. Even though IANAL, I am pretty sure nothing in this commit would qualify for copyright at all.

You are of course correct. However, as I tried to explain above, it is not just policy reasons, it is technical reasons which find their origin in the policy. And that the PR gets marked as "Closed" does not mean that it is rejected or not appreciated. 

Again I am sorry that this made you feel so discouraged about contributing to Gentoo in the future. Perhaps I should have explained better in my first post. It was not my intention to make you feel this way.

> I get the exact same error as yesterday.

Now about the manifest issue, I re-generated the Manifest again in https://github.com/gentoo/sci/commit/bf0b7c9904f8845d1411a6423f1443a21aa70d85 . If it breaks again, than there must be something strange about these tarballs, perhaps they contain a timestamp or something else that makes the hash change every now and then. Maybe we should use the tarballs from PyPI instead, though those tarballs do not contain the docs or the tests for this package. So using those tarballs would mean dropping support for the docs and the tests, which I would like to avoid if at all possible.

**Comment by mschilli87** [comment]
I got the the part on the reason this was changed and I apologize for lashing out. I understand you meant well and a 'Thx for the PR, I merged this manually and bumped the version' instead of 'I cannot merge this because you didn't do X, but I went ahead and fixed it myself' would have made me feel better. But ultimately, it doesn't matter. I did not submit this for credit or some fancy tickbox on my GitHub profile. I couldn't care less. I just want to use snakemake, and wanted to share my solution to a problem I hit.

So I assume we are both fine and can tackle the technical issue (much more fun anyways).

I went ahead and pulled the repo again followed by yet another try to update snakemake to 5.32.2.

This time the checksum checked out (pun absolute intended) so it seems I am good until the next rebuild.
If I hit this again, I can follow up. But for now I unmasked that specific version only preventing automatic updates and since I keep distfiles of installed packages around, even a rebuild triggered by some preserved library or changes USE flags should not cause any symptoms on my system specifically.

**Comment by thesamesam** [comment]
(FWIW, I usually use git commit --author to give credit in such cases).

**Comment by AndrewAmmerlaan** [comment]
> This time the checksum checked out (pun absolute intended) so it seems I am good until the next rebuild.
> If I hit this again, I can follow up. But for now I unmasked that specific version only preventing automatic updates and since I keep distfiles of installed packages around, even a rebuild triggered by some preserved library or changes USE flags should not cause any symptoms on my system specifically.

I'm glad it's working now and that we got this sorted out. If it happens again we'll just have to start using the PyPI tarballs instead for this package.

**Pull request closed without merging**
