### PR TITLE
dev-python/snakemake: add PYTHON_COMPAT version 3.6

### PR DESCRIPTION
**Pull request by linux923344**
Signed-off-by: Marcin Wozniak y0rune@aol.com

### CODE REVIEW

**Comment by TheChymera** [comment]
@linux923344 please squash your commits into one.

**Comment by heroxbd** [comment]
> @linux923344 please squash your commits into one.

I will merge this PR because of https://bugs.gentoo.org/695742 for emergency.

**Comment by y0rune** [comment]
I'm so sorry about not squashed my commits into one. I must study for exam in Collage :(

**Comment by heroxbd** [comment]
> I'm so sorry about not squashed my commits into one. I must study for exam in Collage :(

No problem, you can come back with the knowledge covered in https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Pull request closed without merging**
