### PR TITLE
sci-biology/kat: various fixes for issue #867

### PR DESCRIPTION
**Pull request by kiwifb**
Package-Manager: Portage-2.3.24, Repoman-2.3.6

### CODE REVIEW

**Comment by mmokrejs** [comment]
Thanks for your work, actually I realized I have no rights over https://github.com/gentoo/sci some maybe @jlec or @SoapGentoo would help here? The only thing I could is to take the patch and commit it straight into git+ssh://git@git.gentoo.org/proj/sci.git . I shall better wait for others, it probably won't take too long anyway.

**Comment by mmokrejs** [comment]
Here is at least output from `MAKEOPTS=-j1 FEATURES=noclean emerge =sci-biology/kat-9999`.

[build.log.txt](https://github.com/gentoo/sci/files/1957899/build.log.txt)

**Comment by mmokrejs** [comment]
Updating output from MAKEOPTS=-j1 FEATURES=noclean emerge =sci-biology/kat-9999.

[build.log.txt](https://github.com/gentoo/sci/files/1957976/build.log.txt)

and

`equery files =sci-biology/kat-9999 > /tmp/files.txt`

[files.txt](https://github.com/gentoo/sci/files/1957978/files.txt)

**Comment by kiwifb** [comment]
OK, so there is still only one python installed for you. I will have to get a minimal python3.5 install to test this myself. Anyone has documentation on fixing the rpath?

**Comment by kiwifb** [comment]
Yes rpath problem still present in pure gentoo. Now let's give some attention to your multi-python problem. I have a feeling it will require a split or some very complicated gymnastics. Can you replace `default` in `src_prepare` by `distutils-r1_src_preprare` and see if it improves things.

**Comment by mmokrejs** [comment]
> Can you replace default in src_prepare by distutils-r1_src_prepare and see if it improves things.

I do not think so.

[build.log.txt](https://github.com/gentoo/sci/files/1958238/build.log.txt)

**Comment by mmokrejs** [comment]
@kiwifb Please check whether https://github.com/gentoo/sci/commit/f373141b6dd59db5eaf1bce4104e5ba6085958ac is correct/complete. I tried to squash and rebase a few times, resolve merge conflicts, I wish I did not screw up this. The `DEPPEND` was I guess a typo. Why did not `repoman` catch that?

**Comment by kiwifb** [comment]
Was a typo, and repoman should check that `DEPEND` is set. It doesn't care about a random variable it doesn't know anything about. Spotting that it is a typo is hard unless you put some kind of matching engine behind.

The only wrong with the overlay right now is that there are patches for kat-2.4.1 when there is no kat-2.4.1 ebuild anymore and the patches are not used by any other ebuilds.

**Comment by mmokrejs** [comment]
But the patches **are** used by 2.4.2 and -9999. Yes, I could have renamed them, true. Yes, the old patches I dropped but I thought that was because of my tree being outdated, not because of your branch.

**Comment by mmokrejs** [comment]
Aha, I wanted to say two patches are still used (probably due to me screwing the merges they stay with the old filenames). In manual resolving of the failed merge I had to bring the patch file lines back in ebuilds. I will rename them on disk, I thought you objected not even the two remaining patches should be used anymore.

**Comment by kiwifb** [comment]
Yeah, I thought about redo-ing the branch from scratch. May be I should have :)

**Comment by mmokrejs** [comment]
Aha, I am really sleepy, sorry. Now I see what you said. There are still extra the '2.4.1' versions. Removed in 2ae549fb69309b8ab8537b3e9a8ea158d375cf1d .

**Pull request closed without merging**
