### PR TITLE
Tree-clean: I do no longer maintain these ebuilds.

### PR DESCRIPTION
**Pull request by timeraider4u**
Package-Manager: Portage-2.3.6, Repoman-2.3.1

### CODE REVIEW

**Comment by heroxbd** [comment]
Could you please make an announcement to the gentoo science mailing list https://archives.gentoo.org/gentoo-science/?  Someone might step up to take care of these packages.

**Comment by timeraider4u** [comment]
Yes, thanks for the good point. I have sent a mail in https://archives.gentoo.org/gentoo-science/message/ab4092bd3c5f9f892c162e9818ee3662

If somebody steps up, I will close this bug. Otherwise I will report back in exactly one month.

**Comment by timeraider4u** [comment]
More than one month passed since I have announced the removal of my ebuilds. No one was interested in maintaining or keeping these ebuilds. Please merge my pull request. Thanks!

**Comment by timeraider4u** [comment]
Dist-tarballs will be removed within the next 7 days.

**Pull request closed without merging**
