### PR TITLE
sci-biology/bx-python: drop py3.6, add dep on cython and six  add blocker with RSeQC

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
Package-Manager: Portage-3.0.12, Repoman-3.0.2
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@riseup.net>

### CODE REVIEW

**Comment by mmokrejs** [comment]
Seems py3 fixes were not yet released, see e.g. https://github.com/bxlab/bx-python/commit/500a4825f89884b930b9c523ad15b997bc655e5f . I would not be surprised the package was not yet fully migrated to py3. Maybe worth keeping the -9999 ebuild?

**Comment by AndrewAmmerlaan** [comment]
> Seems py3 fixes were not yet released, see e.g. [bxlab/bx-python@500a482](https://github.com/bxlab/bx-python/commit/500a4825f89884b930b9c523ad15b997bc655e5f) . I would not be surprised the package was not yet fully migrated to py3. Maybe worth keeping the -9999 ebuild?

Sure, I'll re-add it.

**Comment by TheChymera** [comment]
@AndrewAmmerlaan why “make repoman happy”? on my end repoman doesn't complain...

**Comment by AndrewAmmerlaan** [comment]
> @AndrewAmmerlaan why “make repoman happy”? on my end repoman doesn't complain...

I get this:

```
RepoMan scours the neighborhood...
dependency.badindev           4
sci-biology/bx-python/bx-python-0.8.9.ebuild: BDEPEND: ~amd64-linux(default/linux/amd64/17.0/no-multilib/prefix/kernel-3.2+)
['dev-lang/python:3.7', 'dev-lang/python:3.8', 'dev-lang/python:3.9']
sci-biology/bx-python/bx-python-0.8.9.ebuild: RDEPEND: ~amd64-linux(default/linux/amd64/17.0/no-multilib/prefix/kernel-3.2+)
['dev-lang/python:3.7', 'dev-lang/python:3.8', 'dev-lang/python:3.9']
sci-biology/bx-python/bx-python-0.8.9.ebuild: BDEPEND: ~amd64-linux(default/linux/amd64/17.1/no-multilib/prefix/kernel-3.2+)
['dev-lang/python:3.7', 'dev-lang/python:3.8', 'dev-lang/python:3.9']
sci-biology/bx-python/bx-python-0.8.9.ebuild: RDEPEND: ~amd64-linux(default/linux/amd64/17.1/no-multilib/prefix/kernel-3.2+)
['dev-lang/python:3.7', 'dev-lang/python:3.8', 'dev-lang/python:3.9']
RepoMan sez: "You're only giving me a partial QA payment?
I'll take it this time, but I'm not happy."
```

It's not a fatal error or an important warning or anything, but I fixed this one as well while I was at it.

**Comment by TheChymera** [comment]
@AndrewAmmerlaan ah, ok, only with the -d flag

```
chymera@silenthost ~/src/sci/sci-biology/bx-python $ repoman full

RepoMan scours the neighborhood...

Note: use --include-dev (-d) to check dependencies for 'dev' profiles

RepoMan sez: "If everyone were like you, I'd be out of business!"
chymera@silenthost ~/src/sci/sci-biology/bx-python $ repoman full -d

RepoMan scours the neighborhood...
  dependency.badindev           4
   sci-biology/bx-python/bx-python-0.8.9.ebuild: BDEPEND: ~amd64-linux(default/linux/amd64/17.0/no-multilib/prefix/kernel-3.2+)
['dev-lang/python:3.7', 'dev-lang/python:3.8', 'dev-lang/python:3.9']
   sci-biology/bx-python/bx-python-0.8.9.ebuild: RDEPEND: ~amd64-linux(default/linux/amd64/17.0/no-multilib/prefix/kernel-3.2+)
['dev-lang/python:3.7', 'dev-lang/python:3.8', 'dev-lang/python:3.9']
   sci-biology/bx-python/bx-python-0.8.9.ebuild: BDEPEND: ~amd64-linux(default/linux/amd64/17.1/no-multilib/prefix/kernel-3.2+)
['dev-lang/python:3.7', 'dev-lang/python:3.8', 'dev-lang/python:3.9']
   sci-biology/bx-python/bx-python-0.8.9.ebuild: RDEPEND: ~amd64-linux(default/linux/amd64/17.1/no-multilib/prefix/kernel-3.2+)
['dev-lang/python:3.7', 'dev-lang/python:3.8', 'dev-lang/python:3.9']
RepoMan sez: "You're only giving me a partial QA payment?
              I'll take it this time, but I'm not happy."
```

Well, since this also seems to include dependency specification improvements, I'll pull, but really I think it would be best to prioritize more substantial fixes, we have heaps of packages which are actually broken, as shown by our mask list, and we should determine whether they can be salveged/updated or can be safely scrapped.

Also, please update the commit text to something more descriptive. Thank you :3

**Comment by AndrewAmmerlaan** [comment]
> Also, please update the commit text to something more descriptive. Thank you :3

Updated

> Well, since you already went through the trouble of submitting a PR, and this also seems to include dependency specification improvements, I'll pull, but really I think it would be best to prioritize more substantial fixes, we have heaps of packages which are actually broken, as shown by our mask list, and we should determine whether they can be salvaged/updated or can be safely scrapped.

https://github.com/gentoo/sci/pull/1025 https://github.com/gentoo/sci/pull/1024 and https://github.com/gentoo/sci/pull/1014 fix some masked packages. I might have time to fixup some more of those masked and/or ancient ebuilds tomorrow :smiley: .

**Comment by TheChymera** [comment]
> #1025 #1024 and #1014 fix some masked packages

Those and a few others IIRC, thank you for that! In any case, whatever contibutions you are willing to make are gratefully received :) Just highlighting that we sadly still have far bigger issues than repoman failures in developer mode :cry:

**Pull request closed without merging**
