### PR TITLE
sci-libs/h5zstd: Add zstd compress filter for hdf5

### PR DESCRIPTION
**Pull request by littlewu2508**
Introduce the Zstandard compression filter plugin for HDF5 to Gentoo via this ebuild. Also upport Gentoo-Prefix.

Package-Manager: Portage-3.0.5, Repoman-3.0.1
Signed-off-by: Benda Xu <heroxbd@gentoo.org>

### CODE REVIEW

**Comment by epsilon-0** [comment]
Why does this have heroxbd's sign off?
You should sign this with your own name and email.

**Comment by heroxbd** [comment]
> Why does this have heroxbd's sign off?
> You should sign this with your own name and email.

+1

@littlewu2508 I will sign-off on my own, after I review your ebuild and before I commit it to the tree.

**Comment by heroxbd** [comment]
I think using the upstream name `HDF5Plugin-Zstandard` would be better.

**Comment by littlewu2508** [comment]
> 
> 
> I think using the upstream name `HDF5Plugin-Zstandard` would be better.

OK. Because the package name changed, I created a new pull request: [](https://github.com/gentoo/sci/pull/987).

> 
> 
> Why does this have heroxbd's sign off?
> You should sign this with your own name and email.

Signing message corrected in the new pull request.

**Pull request closed without merging**
