### PR TITLE
sci-libs/ciftilib: add qtcore alternative dep and compatibility

### PR DESCRIPTION
**Pull request by kiwifb**
Package-Manager: Portage-2.3.49, Repoman-2.3.11

### CODE REVIEW

**Comment by kiwifb** [comment]
Changes:
* more compatibility with fsl's nifti_io
* add openmp flag to .pc file if used
* build shared library

**Comment by TheChymera** [comment]
@kiwifb I'm unsure how SPAdes is related. Are you sure that's not by mistake? In any case, could you please rebase?

**Comment by kiwifb** [comment]
Ping? Are you still worried about that commit? It is part of the master branch already https://github.com/gentoo/sci/commit/f7eaea4317cca5c6ca5566c05c69b604d7312bc8

**Comment by TheChymera** [comment]
I have push access but I don't know how to rebase this all on your behalf and push so that the commit is also attributed to you.

I know it's an immediately irrelevant technicality, but I'm trying to figure out how to do this properly (esp since I might have to do it more in the future). And I haven't figured it out yet. Ideas?

**Comment by kiwifb** [comment]
No, I am sorry to say.

**Comment by TheChymera** [comment]
If I can't figure this out until tomorrow I will be very ashamed and just reauthor commit the changes myself. Hope that's ok with you.

**Comment by TheChymera** [comment]
please redo it then, one single commit with all your (and only your) changes I can handle :)

**Comment by kiwifb** [comment]
Done.

**Comment by TheChymera** [comment]
Done 6a917c1243b83065c81e4d82c78a6022891df3ef

**Pull request closed without merging**
