### PR TITLE
samtools, bcftools, htslib and hisat2 version bump

### PR DESCRIPTION
**Pull request by khumarahn**
hi!

### CODE REVIEW

**Comment by khumarahn** [comment]
ping?

**Comment by khumarahn** [comment]
still ping

**Comment by heroxbd** [comment]
@SoapGentoo I see you have removed `sci-libs/htslib`, `sci-biology/bcftools` and `sci-biology/samtools` from the overlay.  Would you please justify if this PR should be closed as obsolete?

**Comment by SoapGentoo** [comment]
1. most of the htslib 1.9 stack is in `::gentoo`
2. please add hisat there too, not in the dreadful sci repo
3. for any USE flag functionality in the htslib stack, please rebase your additions on mine

**Pull request closed without merging**
