### PR TITLE
dev-libs/intel-common: version bump to 19.0.3.199

### PR DESCRIPTION
**Pull request by hoefling**
Also adapted `intel-sdp-r1.eclass` and inheriting ebuilds to use `EAPI=7`.

### CODE REVIEW

**Comment by hoefling** [comment]
If the overlay maintainers agree with the proposed changes, I will introduce another two PRs for `=dev/lang-icc-19.0.3.199` (hoefling/sci#dev-lang/icc) and `=dev/lang-ifc-19.0.3.199` (hoefling/sci#dev-lang/ifc).

**Comment by TheChymera** [comment]
Hello @hoefling , sorry for the lack of responsiveness, the overlay maintainer team is a collection of people from different fields specializing on and mainly concerned with specific package subsets, so if none of us is in your field, it takes a long time for someone to get to it.

At any rate, the PR looks good to me. Would it be possible to add a test functionality to the new intel-common version, so that I can check if it actually builds fine?

**Comment by hoefling** [comment]
Hey @TheChymera, no worries - there's no rush. Also thank you for reviewing! Can you point me at some examples for the library ebuild tests as tbh I've never done that before. I can find a license check test for ICC/IFC in the `intel-sdp-r1.eclass`, but I doubt if this is of any use here.

**Comment by TheChymera** [comment]
@hoefling Ebuilds commonly have a test phase defined at the end. This runs the test suite of the package, which most packages distribute to check that they are still doing what they are supposed to do. If you don't know what they use, it's best to either ask upstream or inspect their code with `grep`. There's a few standardized ways to run tests, but a lot of package maintainers get creative at some point.

For examples on how this is implemented in existing packages, run `qgrep "test()" -A10 -H`. Generally, `qgrep` for ebuilds and `grep`/`ag` for the upstream source code will help you a lot.

**Comment by hoefling** [comment]
I took a look at the ebuilds; the packages usually include the tests along with the source code. However, ICC is already precompiled and doesn't include any tests. I could write my own tests using the samples from [Intel C++ Compiler Code Samples](https://software.intel.com/en-us/code-samples/intel-compiler/all-samples-and-downloads) page (compile the sample, run, check for exit code), but am unsure about how to access them in the ebuild:

* I could include them via `SRC_URI`, but because of `RESTRICT="mirror fetch"` in `intel-sdp-r1.eclass`, one would need to download them manually and place under `/usr/portage/distfiles/`. Surely not something everyone will have fun with.

* I could bundle the source code for the samples and access them via `FILESDIR`, but this will blow up the ebuild. Also, I'm not sure about the [license agreement for the samples code](https://software.intel.com/en-us/license/intel-sample-source-code-license-agreement), whether it permits (re)distribution of the source code.

Do you maybe have another idea?

**Comment by TheChymera** [comment]
> I could write my own tests

No, this is not a good idea. We should use tests as specified by upstream. If upstream **really** has no tests, you can contribute them to upstream, and include them in the next release.

If they just use a separate package for testing, it's common to add `test?` to `SRC_URI` in order to conditionally download the testing packages. ITK-5.0_rc1 for example does that:

```
SRC_URI="
	https://github.com/InsightSoftwareConsortium/ITK/archive/v${MY_PV}.tar.gz
	test? ( https://github.com/InsightSoftwareConsortium/ITK/releases/download/v5.0rc01/InsightData-${MY_PV}.tar.gz )
	"
```

**Comment by hoefling** [comment]
`intel-common` doesn't have any tests; it is a non-free dist, requiring a purchased license and is shipped precompiled.

**Comment by TheChymera** [comment]
@hoefling closed in https://gitweb.gentoo.org/proj/sci.git/commit/?id=87b52a55dc7be942f0ca4011bb120a7d65c9802e and
https://gitweb.gentoo.org/proj/sci.git/commit/?id=7b1e850f4e0c6dd53ce6aae1083c6447ead13fbc .

Please close this PR, and, if you have time and are willing to help us out, you're welcome to test other PRs as well and ping me :)

**Pull request closed without merging**
