### PR TITLE
Fixes for sci-biology/fsl-6.0.4 - cstd and new version

### PR DESCRIPTION
**Pull request by AbstractMethod**

### CODE REVIEW

**Comment by AbstractMethod** [comment]
@TheChymera Allright, just created this new PR.

**Comment by TheChymera** [comment]
@AbstractMethod sorry to keep getting back to you with things, not sure if I missed this or it's a new issue. I suspect the latter.

Please always remember to run `repoman full` in the package directory, it checks for common mistakes, such as:

```console
chymera@silenthost ~/src/sci/sci-biology/fsl $ repoman full

RepoMan scours the neighborhood...
  digest.missing [fatal]        1
   /home/chymera/src/sci/sci-biology/fsl::fsl-6.0.4.tar.gz
  file.size [fatal]             2
   (29 KiB) sci-biology/fsl/files/fsl-6.0.4-remove_fslpy_collisions.patch
   (23 KiB) sci-biology/fsl/files/fsl-6.0.4-fsldir_redux.patch
   ```
   
The first one can be solved by running `ebuild fsl-6.0.4.ebuild manifest`.
The latter issue is a bit more tricky. Portage doesn't want you to track files which are too large over it.
The best approach would be to host these patches (if you have your own stable server space), and download them in `SRC_URI`.
Alternatively I can host them for you, and send you the links for `SRC_URI`, but this would add some asynchrony if you ever want to improve this (i.e. you'd need to check in with me in parallel with your PR to change or update the resources). If at all possible, since you're the author of the fix, I think you should be in control of the resources.

**Comment by AbstractMethod** [comment]
@TheChymera thanks for this, but at this point I'm running out of patience with this.

If you want to host than by all means, but I have no stable server space available.

**Comment by TheChymera** [comment]
@AbstractMethod I understand, I often felt similarly frustrated when I started contributing and bumped against all of the specific requirements. I would recommend trying to pull through regardless, as these things are not as difficult as they first seem — and as soon as you have them down pat you can get push access and contribute at your own leisure and without having to wait for anybody :)

Barring that, I will get to this as soon as I finish my current work on SimpleITK and AFNI :)

**Comment by AbstractMethod** [comment]
@TheChymera OK, I reduced the sizes of the patches by splitting them up into smaller ones. repoman checks pass now.

**Comment by AndrewAmmerlaan** [comment]
Merged after making some minor changes (added some || die, http --> https)

Thanks :+1:

**Pull request closed without merging**
