### PR TITLE
sci-biology/spm: fix Manifest having wrong filesize

### PR DESCRIPTION
**Pull request by waebbl**
Hello, I was trying to install the spm-12_p6470 package, when I got an error with the recorded file size, which seems no longer be valid.

```
>>> Downloading 'http://www.fil.ion.ucl.ac.uk/spm/download/restricted/eldorado/spm12.zip'
--2018-09-15 08:59:37--  http://www.fil.ion.ucl.ac.uk/spm/download/restricted/eldorado/spm12.zip
Resolving www.fil.ion.ucl.ac.uk (www.fil.ion.ucl.ac.uk)... 193.62.66.18
Connecting to www.fil.ion.ucl.ac.uk (www.fil.ion.ucl.ac.uk)|193.62.66.18|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 99848067 (95M) [application/zip]
Saving to: ‘/mnt/data/download/portage/distfiles/spm-12_p6470.zip’

/mnt/data/download/ 100%[===================>]  95.22M  10.8MB/s    in 9.0s    

2018-09-15 08:59:47 (10.6 MB/s) - ‘/mnt/data/download/portage/distfiles/spm-12_p6470.zip’ saved [99848067/99848067]

!!! Fetched file: spm-12_p6470.zip VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      99848067
!!! Expected: 97172673
```

To validate this, I downloaded the file manually from their download langing form and compared the size and md5sum with the numbers from the file I got by running ebuild --force spm-12_p6470.ebuild manifest, which were equal.

Please check and validate the new digest in the Manifest from this PR.

Note, that I didn't address the minor issues in the package, repoman was complaining about (deprecated use of versionator, deprecated eapi usage, upstream.workaround). Just wanted to install the package.

Package-Manager: Portage-2.3.49, Repoman-2.3.10

### CODE REVIEW

**Comment by TheChymera** [comment]
@waebbl sorry for taking so long.

```
MY_PV=$(get_major_version)
...
SRC_URI="http://www.fil.ion.ucl.ac.uk/spm/download/restricted/eldorado/${PN}${MY_PV}.zip -> ${P}.zip"
```

This suggests to me that the upstream archive has been updated. I guess the correct thing to do is to delete this package and bumped to a new one. You would need to find out the correct new number analogous to `p6470`. Can you do this?

Going forward, seeing that upstream does this, we should take care to reposit the new archive in the Gentoo devspace. E.g. in the webspace of a developer. So this either has to wait until I get that, or another developer decides to help. Having said that, this is not your problem :) You can just go ahead and bump the package to the new `p*` version. As soon as you do that, I can try and take care of the rest. We could also restore this version, but for that you would need to dig up a copy of the `spm-12_p6470` archive.

**Comment by waebbl** [comment]
So I found out two things:
According to https://www.fil.ion.ucl.ac.uk/spm/download/spm12_updates/ the current number should be `7219`.
However, at https://www.fil.ion.ucl.ac.uk/spm/download/restricted/eldorado/ the current release of `spm_12.zip` seems to actually be spm_12.3, released November 2017.
Looking into the readme file of the updates site, release 12.3 should be equal to `r6906`, released October 2016.
Because the `r7219` update has the same release date as the `spm_12.3.zip`, the 12.3 release could be the same as the `r7219`.

**Comment by waebbl** [comment]
So what about getting away from the `_p<nnnn>` versioning and just switch over to the versioning they use on their download page. They have versions 12.1 to 12.3 for download there. IIRC, from the readme at the update page, `p6470` should belong to 12.1.

**Comment by TheChymera** [comment]
Can you check whether `12.1` has the same checksum as what we recorded for `p6470`? If not, please check with upstream so that we know where we can get static archives from.

**Comment by TheChymera** [comment]
Can you check whether `12.1` has the same checksum as what we recorded for `p6470`? If not, please check with upstream so that we know where we can get static archives from.

**Comment by TheChymera** [comment]
Can you check whether `12.1` has the same checksum as what we recorded for `p6470`? If not, please check with upstream so that we know where we can get static archives from.

**Comment by TheChymera** [comment]
Can you check whether `12.1` has the same checksum as what we recorded for `p6470`? If not, please check with upstream so that we know where we can get static archives from.

**Comment by TheChymera** [comment]
Can you check whether `12.1` has the same checksum as what we recorded for `p6470`? If not, please check with upstream so that we know where we can get static archives from.

**Comment by TheChymera** [comment]
Can you check whether `12.1` has the same checksum as what we recorded for `p6470`? If not, please check with upstream so that we know where we can get static archives from.

**Comment by TheChymera** [comment]
Can you check whether `12.1` has the same checksum as what we recorded for `p6470`? If not, please check with upstream so that we know where we can get static archives from.

**Comment by TheChymera** [comment]
Can you check whether `12.1` has the same checksum as what we recorded for `p6470`? If not, please check with upstream so that we know where we can get static archives from.

**Comment by kiwifb** [comment]
Stop submitting again and again we get it.
Github has trouble that’s probably why the issue isn’t updating.
https://status.github.com/messages

**Comment by waebbl** [comment]
I'll look into it.

**Comment by waebbl** [comment]
@TheChymera Yes `spm12.1.zip` has the same sums as the recorded ones (sha256, sha512, whirlpool all match).

**Comment by waebbl** [comment]
@TheChymera  I can create the PR.

TBH, I haven't really tested it. I found it once on your neurogentoo overlay, and, since I'm working at a neurological hospital, I was thinking it could be worth to check it out, but other projects boxed it out of focus. I'm actually not much into neuro-imaging topics and only wanted to test it, to see, whether it could be worth to recommend it to some of our physicians or to the CT staff.

**Comment by TheChymera** [comment]
@waebbl well, go ahead and create (or update) the PR for the additions. It could actually be that a lot of SPM/octave works now. I talked back and forth with Guillaume Flandin ( @gllmflndn ) about this, and he stated that significant improvements have been made. You can email him (and add me in CC) if after you have emerged this you have any significant feedback.

**Comment by gllmflndn** [comment]
@TheChymera, @waebbl : all of the SPM12 releases are also available on GitHub:
  https://github.com/spm/spm12/releases
There will be a new update in the next few weeks.

Concerning compatibility with Octave, it's consistently improving over time but mainly to be used from the command line (ie not the GUI).

@waebbl : if you just want to test SPM in the context of your hospital, you might want to check[ SPM Standalone](https://en.wikibooks.org/wiki/SPM/Standalone).

**Comment by waebbl** [comment]
@gllmflndn Thanks for your input! Good to know it's also hosted on GitHub. As for the SPM Standalone, I might give it a try, when I have a little more time. Maybe the octave has already improved as much to test it there.
One thing popped up yesterday when I tested my build script. I got a QA warning about not respected `CFLAGS` and `LDFLAGS`. I looked at the options for `mkoctfile` and the SPM Makefiles, but there are no `CFLAGS` or `LDFLAGS` passed to the octave compiler. Requesting it's value for those variables using the `-p` switch it returns the default values for machine at the compile time of octave. Any ideas how this warnings could be solved?

@TheChymera: the releases on GitHub uses the `_rXXXX` schema again, in contrast to the FIL download area. I suspect, I'm going back then to the old version scheming.

**Comment by gllmflndn** [comment]
The only place I can think of where CFLAGS are adjusted is here:
https://github.com/spm/spm12/blob/master/%40gifti/private/Makefile#L13
Is this what Gentoo QA is complaining about?

**Comment by waebbl** [comment]
It could be part of it. It basically complains about (almost?) any `.mex` and `.mexa64` file being built.
```
 * QA Notice: Files built without respecting CFLAGS have been detected
 *  Please include the following list of files in your report:
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/toolbox/FieldMap/pm_create_connectogram_dtj.mexa64
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/toolbox/FieldMap/pm_estimate_ramp.mexa64
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/toolbox/FieldMap/pm_ff_unwrap.mexa64
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/toolbox/FieldMap/pm_invert_phasemap_dtj.mexa64
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/toolbox/FieldMap/pm_merge_regions.mexa64
...
```
and

```
* QA Notice: Files built without respecting LDFLAGS have been detected
 *  Please include the following list of files in your report:
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/@file_array/private/file2mat.mex
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/@file_array/private/file2mat.mexa64
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/@file_array/private/init.mex
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/@file_array/private/init.mexa64
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/@file_array/private/mat2file.mex
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/@file_array/private/mat2file.mexa64
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/@gifti/private/zstream.mex
 * /usr/share/octave/4.4.0/site/m/spm-12_p7219/@gifti/private/zstream.mexa64
...
```

This is only the top of the output. It contains for example also the `@gifti/private/zstream.mex{,a64}` files.
But the compilation of `ztream.c` doesn't show any modification of `CFLAGS`:
```
make[1]: Entering directory '/var/tmp/portage/sci-biology/spm-12_p7219/work/spm12-r7219/@gifti/private'
mkoctfile --mex zstream.c 
make[1]: Leaving directory '/var/tmp/portage/sci-biology/spm-12_p7219/work/spm12-r7219/@gifti/private'
```

That's how almost all files are being compiled, with the exception of a few files where a `-D` flag is added at the end.

That said, it doesn't fail the build. I can successfully compile and install both ebuild I submitted yesterday.

**Comment by gllmflndn** [comment]
I would ignore all of the warnings about *.mexa64 files as they are the MATLAB ones (you might actually want to delete all *.mex* files from the SPM distribution before compiling the Octave *.mex files).

Otherwise I don't understand what the QA test is looking for (would you have a link to the script actually used?), so it's hard for me to comment. It seems to be more of a possible issue with `mkoctfile` than with SPM though.

**Comment by waebbl** [comment]
I actually run `make distclean` before compiling, so I assumed, the sources are clean and all library files are produced during compilation (see https://github.com/gentoo/sci/pull/884/commits/2951f8b14e9c5b8dad1ca353b2d1b397c50b01bf#diff-5469c1088ebc8ba225bbc23f22c76c24R25 as well as line 29 and 33, just assume `emake == make`). I might have to improve the upfront cleaning then to delete those extra files as well. Thanks for this hint.

I'm too thinking the issue is probably related to `mkoctfile` and not the SPM makefiles.

As for the QA, this actually happens inside portage (the package manager). I don't know much about the internals of portage, but I see whether I can come up with the code that's actually doing the QA checks.
What it is basically doing is: On Gentoo the package manager uses a global config file, for the user to provide `CFLAGS`, `LDFLAGS` and other variables for global use for package building. Any package is expected to respect those flags, thus, if a package has need for some special values added to those flags, they must not override the given flags, but add them, i.e. using for example `CFLAGS+=-fmy_flag` instead of `CFLAGS=-fmy_flag`. Whenever a package uses the latter one, portage will detect it and throws such a QA warning.

**Comment by gllmflndn** [comment]
`make distclean` in SPM will only clean the repository for the platform it is running on: in your case it will only remove *.mex files but not the MATLAB ones for Windows/Linux/Mac.

Thanks for the explication about the QA checks  - I understand a bit more. If we only look at the *.mex files, do you get the QA warnings for CFLAGS and LDFLAGS or LDFLAGS only?

**Comment by gllmflndn** [comment]
Is it related to this? https://savannah.gnu.org/bugs/?48678

**Comment by waebbl** [comment]
@TheChymera @gllmflndn Continuation can take place in https://github.com/gentoo/sci/issues/896

Closing this PR now

Thanks @TheChymera for merging.

**Pull request closed without merging**
