### PR TITLE
Rename smartgit-6.5.6.ebuild to smartgit-7.0.3.ebuild

### PR DESCRIPTION
**Pull request by necrose99**
upstream version match

### CODE REVIEW

**Comment by marbre** [comment]
Please check [CONTRIBUTING.md](https://github.com/gentoo-science/sci/blob/master/CONTRIBUTING.md). You're commit breaks the travis build since the Manifest wasn't updated. You should use `repo-commit` or `repoman commit`.

**Comment by necrose99** [comment]
yes I'll revise the manifest. i have hand not a chance to do so yet.

**Comment by jlec** [comment]
@necrose99 Any chance to fix this?

**Comment by TheChymera** [comment]
smartgit is no longer distributed by Gentoo Science. Should you want to bring it back, we can do so pending a current-version PR.

**Pull request closed without merging**
