### PR TITLE
Fsl 6.0.4 cstd fix

### PR DESCRIPTION
**Pull request by AbstractMethod**
@TheChymera new PR -- I'll close the other one.

### CODE REVIEW

**Comment by TheChymera** [comment]
@AbstractMethod have you managed to build this? I get the following error: `ERROR::Could not make fdt successfully` — full [build.log](https://github.com/gentoo/sci/files/6141734/fdt_fail.log).

Is this something you can reproduce and/or fix?

**Comment by AbstractMethod** [comment]
@TheChymera Oops.  Good catch.  Actually have a patch for this (to disable CUDA support for fdt) but was applying it in the wrong place.  It's a simply fix to fsl-6.0.4.ebuild.

**Comment by TheChymera** [comment]
@AbstractMethod thanks for fixing this. Could you please merge the patches (i.e. rebase them in to one)?

**Comment by AbstractMethod** [comment]
Umm... I don't know how to do that (?)

Is there a simple FAQ or something to help?

**Comment by TheChymera** [comment]
@AbstractMethod `rebase -i HEAD~3` where 3 is the number of commits you are trying to merge into one. This will open a text document in which you select how to rebase. I usually use fixup, and sometimes reword for the oldest commit.

**Comment by AbstractMethod** [comment]
@TheChymera OK, that wasn't too hard -- thanks!  It think it's all sorted now.

**Comment by TheChymera** [comment]
@AbstractMethod have you pushed that at the end? It still looks like the same original 3 commits to me.

After you re-write your local commit history you can push it to the remote (assuming your GitHub repo is named `origin`) with `git push -f origin`.

Thanks :)

**Comment by AbstractMethod** [comment]
@TheChymera Something is broken on my end, and I don't know what it is.

My branch seems OK:

    On branch fsl-6.0.4-cstd-fix
    Your branch is ahead of 'origin/master' by 2 commits.
      (use "git push" to publish your local commits)

    nothing to commit, working tree clean

But git push gives me a fatal error about the current branch not matching upstream.  When I try to set it, I get an "Authentication" failed message.

I don't know how to fix this without deleting this pull request and submitting a new one from scratch.

**Comment by TheChymera** [comment]
@AbstractMethod hard for me to debug based solely on that info. If you want to figure this out, I would recommend joining `#git` on freenode IRC. In the interest of time, however, if you're not particularly curious what happened, a fresh PR would be equally good.

Thank you!

**Pull request closed without merging**
