### PR TITLE
sci-biology/fsl: Changes for fsl CUDA support

### PR DESCRIPTION
**Pull request by AbstractMethod**

### CODE REVIEW

**Comment by TheChymera** [comment]
@AbstractMethod thank you for this! @Jimmy2027 was so kind as to help us thest this on on a computer with CUDA. Sadly it did not build. Do you know what might be causing this?

http://109.202.220.6:5000/file/e6a860.log

**Comment by AbstractMethod** [comment]
OK, I'm confused.  It looks like my cuda specific patches were applied, but in the wrong place?!?

    * Applying fsl-6.0.2-eddy_cuda.patch ...                  
    * Applying fsl-6.0.2-cuda_buildsettings.patch ...

Those patches should only be applied with the `cuda` USE flag set -- but if that were the case I don't understand how the other code could not have also executed, which would replace `@@GENTOO_NVCC_FLAGS@@` with the correct `gcc` directory that`nvcc` should compile against.

On my box the relevant lines from the build log look like:

    >>> Preparing source in /var/tmp/portage/sci-biology/fsl-6.0.2-r1/work/fsl ...
    * Applying fsl-6.0.2-gcc10_include.patch ...                                 [ ok ]
    * Applying fsl-6.0.2-setup.patch ...                                         [ ok ]
    * Applying fsl-6.0.2-template.patch ...
    patching file src/newimage/generalio.cc
    patching file src/fslsurface/fslsurfaceio.cc
    Hunk #1 succeeded at 1055 with fuzz 2.                                        [ ok ]
    * Applying fsl-6.0.2-no_xmlpp.patch ...                                      [ ok ]
    * Applying fsl-5.0.11-niftiio_var_fix.patch ...                              [ ok ]
    * Applying fsl-5.0.11-ifstream_use.patch ...                                 [ ok ]
    * Applying fsl-5.0.11-fslsurface_parallel_make.patch ...                     [ ok ]
    * Applying fsl-6.0.2-qstring_compat.patch ...                                [ ok ]
    * Applying fsl-5.0.9-headers.patch ...                                       [ ok ]
    * Applying fsl-6.0.2-fsldir_redux.patch ...                                  [ ok ]
    * Adjusting to prefix /
    *   fast_two.cc ...                                                          [ ok ]
    *   tsplot.cc ...                                                            [ ok ]
    *   first_utils.cc ...                                                       [ ok ]
    *   fnirtfns.cpp ...                                                         [ ok ]
    *   fslsurface_first.cc ...                                                  [ ok ]
    *   miscpic.h ...                                                            [ ok ]
    *   melreport.h ...                                                          [ ok ]
    *   melreport.cc ...                                                         [ ok ]
    *   mixture_model.cc ...                                                     [ ok ]
    *   topupfns.cpp ...                                                         [ ok ]
    *   label-div.html ...                                                       [ ok ]
    * 
    * GCC version: 9.3.0
    * CUDA GCC path: /usr/x86_64-pc-linux-gnu/gcc-bin/8.4.0
    *   --compiler-bindir "/usr/x86_64-pc-linux-gnu/gcc-bin/8.4.0"
    * Applying fsl-6.0.2-eddy_cuda.patch ...                                     [ ok ]
    * Applying fsl-6.0.2-cuda_buildsettings.patch ...                            [ ok ] 

From the given build log it looks like they were somehow applied 'early', and the full information lines regarding GCC at the bottom here are not executed at all. (?)

**Comment by AbstractMethod** [comment]
@TheChymera @Jimmy2027: Is it possible for me to see the .ebuild that was executed on the test machine?  I'm really not sure how to rectify the build log you provided with the patch I submitted.

**Comment by Jimmy2027** [comment]
@AbstractMethod I'm not exactly sure what went wrong the first time, but I re-applied your PR and was able to build fsl with the cuda USE flag in the end :)

**Comment by TheChymera** [comment]
@AbstractMethod ok, it's in :) https://gitweb.gentoo.org/proj/sci.git/commit/?id=21789df887204e7b98393fb115982ee36a71d8c1

Thank you!

Please also remember to close the issue.

Not least of all, if you are interested in contributing more regularly, I'm planning to clean house a bit on the overlay, and we have many open issues to solve ( https://travis-ci.com/github/gentoo/sci/builds/184301462 ). you can also always ping me for issues/PRs, I should reply in a timely fashion.

**Comment by AbstractMethod** [comment]
@TheChymera : cool. Will do regarding other issues.

**Pull request closed without merging**
