### PR TITLE
readd scilab-5.5.2 (v2)

### PR DESCRIPTION
**Pull request by efferre79**
@AndrewAmmerlaan 

I have created a cleaner PR for the work described in #1038. In addition I removed the ban on --as-needed because on my system (amd64) I don't see any problem, I would say to open for user tests as is now, we can eventually revert the [commit](https://github.com/gentoo/sci/commit/94126d01335baf5943728111a9849c392cdb22eb).

I have not put any keywords yet but on my (stable) system it seems to work correctly (I have tested xcos too) at runtime, I will leave that step for you.

The ebuild itself builds and works but it still needs two fixes in portage:

1. jython installation (https://bugs.gentoo.org/758881) for batik
2. to address missing symbols for lapack, a lapack[deprecated] dependency is neeeded. In portage currently lapack-3.8.0-r1 offers that functionality but not latest 3.9.0. I have created another PR for that, see [comment 10](https://bugs.gentoo.org/702254#c10)

I think some fixes for 5.5.2 can be ported to 6.x too

### CODE REVIEW

**Comment by efferre79** [comment]
The ebuild name is currently without -r1 (as version resurrected), maybe it makes sense to name it -r2?

**Comment by AndrewAmmerlaan** [comment]
Thanks! :smile: 

> I think some fixes for 5.5.2 can be ported to 6.x too

I ported some of the trivial changes (dependencies and such) to the 6.x versions, I'll see if I can use some of the patches for the 5.5.2 version to get the 6.x versions up and running as well.

> I have not put any keywords yet but on my (stable) system it seems to work correctly (I have tested xcos too) at runtime, I will leave that step for you.

After adding a dependency on ant-junit4 and adding `append-fflags -fallow-argument-mismatch` (required for gcc>=10) it also compiles and runs just fine for me, so I went ahead and added the amd64 keyword.

> The ebuild name is currently without -r1 (as version resurrected), maybe it makes sense to name it -r2?

We could do this, but IMO it is not necessary because this package has been masked and broken for ages.

Thanks again! Now we finally have a working version of scilab in the tree :partying_face:

**Comment by AndrewAmmerlaan** [comment]
@efferre79

After quite some effort I finally managed to get an ebuild working for lucene>3. Scilab-6.x.y now successfully completes the configure phase, but it still fails near the end of the compile phase, complaining about some undefined references. The error seem similar to the one that 5.x.y produced before, how did you fix it in that version?

```
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `changeFontWithProperty'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/ast/.libs/libsciast.so: undefined reference to `types::Inspector::removeItem(types::InternalType*)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `startInteractiveZoom'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `sciJavaUpdateTextBoundingBox'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `sciGetJava2dViewCoordFromPixel'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `sciGetJava2dViewPixelCoordinates'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorShowUnreferencedItem(std::vector<types::InternalType*, std::allocator<types::InternalType*>>&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorGetFunctionList(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `javaClickRubberBox'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `changeFontFromFilename'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorGetItemCount(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorGetUnreferencedItem(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `addFont'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `sciGetJavaViewingArea'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorGetItem(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `isAvailableFontsName'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `getAvailableFontsName'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `getNbInstalledFonts'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `javaDragRubberBox'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorDeleteUnreferencedItems(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `getInstalledFontsName'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `sciJavaUpdateSubwinScale'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `sciGetJava2dViewCoordinates'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `addFontFromFilename'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/graphics/.libs/libscigraphics.so: undefined reference to `resetFontManager'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorShowItem(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/ast/.libs/libsciast.so: undefined reference to `types::Inspector::addItem(types::InternalType*)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1215: scilab-bin] Error 1
make[1]: Leaving directory '/var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2'
make: *** [Makefile:1601: all-recursive] Error 1
```

**Comment by efferre79** [comment]
> After quite some effort I finally managed to get an ebuild working for lucene>3. Scilab-6.x.y now successfully completes the configure phase, but it still fails near the end of the compile phase, complaining about some undefined references. The error seems similar to the one that 5.x.y produced before, how did you fix it in that version?

I didn't face such kind of linker errors for 5.5.2. It seems to me there are missing deps in the building system files, try [removing](https://wiki.gentoo.org/wiki/Project:Quality_Assurance/As-needed) the --as-needed linker flag to see if that is the problem.

**Comment by AndrewAmmerlaan** [comment]
Hmm, with `--no-as-needed` part of the problem goes away, but it still fails with:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/ast/.libs/libsciast.so: undefined reference to `types::Inspector::removeItem(types::InternalType*)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorShowUnreferencedItem(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorGetFunctionList(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorGetItemCount(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorGetUnreferencedItem(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorGetItem(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorDeleteUnreferencedItems(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./modules/.libs/libscilab-cli.so: undefined reference to `sci_inspectorShowItem(std::vector<types::InternalType*, std::allocator<types::InternalType*> >&, int, std::vector<types::InternalType*, std::allocator<types::InternalType*> >&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2/modules/ast/.libs/libsciast.so: undefined reference to `types::Inspector::addItem(types::InternalType*)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1215: scilab-bin] Error 1
make[1]: Leaving directory '/var/tmp/portage/sci-mathematics/scilab-6.0.2/work/scilab-6.0.2'
make: *** [Makefile:1601: all-recursive] Error 1
```
Which is confusing because those functions are defined in `modules/core/sci_gateway/cpp` (and those other functions that it complains about with `--as-needed` are in `modules/renderer/src/java/...`.)

**Comment by efferre79** [comment]
try to see in the log if --no-as-needed is applied everywhere

**Pull request closed without merging**
