### PR TITLE
sci-biology/imagej: bump version imagej sources and plugins

### PR DESCRIPTION
**Pull request by IAHM-COL**
* ImageJ version bump 1.53t to 1.54g from NIH sources
* plugins version bump 153 to 154

### CODE REVIEW

**Comment by IAHM-COL** [comment]
@AndrewAmmerlaan 

This continues the imagej version bumping. There are a few circumstances to be mentioned.

1.  All ebuilds tested for compilation, and pass ok, in my box
2. **Plugins are now available for version 154**, so that gets updated here, fetching from NIH
    -  see https://wsr.imagej.net/distros/cross-platform/
3. The latest version available both github and from NIH is 1.54h, 
    -  see https://imagej.net/ij/download/src/
    - see https://github.com/imagej/ImageJ/tags
5. However two ebuilds can't have same name!  Therefore
     -  I preserved 1.54h from github, same file as 9999
     -  I updated the ebuild from NIH sources to one version below 1.54g
6. Although it would have made technical sense to make 1.54g `stable`, 1.54h `~amd64` and 999 `**` keywords, as we have discussed before, the policy for sci as overlay is to keep `~amd64` and `**` for all ebuilds, as a consequence, 
`pkgcheck scan` still results on 

```
sci-biology/imagej
      RedundantVersion: version 1.54g: slot(0) keywords are overshadowed by version: 1.54h
```

With all this in consideration, I think the version bump is clear for this merge request.

**Comment by AndrewAmmerlaan** [comment]
> However two ebuilds can't have same name! Therefore
> 
>     * I preserved 1.54h from github, same file as 9999
> 
>     * I updated the ebuild from NIH sources to one version below 1.54g

What is the reason we need an ebuild for both locations? Is there some difference in the source files?

**Comment by IAHM-COL** [comment]
> What is the reason we need an ebuild for both locations? Is there some difference in the source files?


I don't know the answer.

I presume, downloading from both sites and running a SHA sum can answer whether the github releases and the source zips on the NIH site are actually mirrors. If you want I can test this for 1.54h. it's too involved to check for many versions.

The NIH site kept the source dir outdated for a significant amount of time, and the releases appeared as tags on github. But they appear to be caught up now.

**Comment by IAHM-COL** [comment]
> I presume, downloading from both sites and running a SHA sum can answer whether the github releases and the source zips on the NIH site are actually mirrors. If you want I can test this for 1.54h. it's too involved to check for many versions.

```
~/test $ ls
ij154h-src.zip  v1.54h.zip
~/test $ sha512sum ij154h-src.zip 
01fa9d3c52aa7a4ba9b2407d6157f75f18c8a3e9ef5ea0e30414671b6fb421574016159fc82718904cfe774c851f50a1da1460ebadd0cdc4b54f9e62691563eb  ij154h-src.zip
~/test $ sha512sum v1.54h.zip 
308db44defcf8672c565bf5481869ce24645bdd716dd70cd282f97f91ab6da17e509244793a5506461a713708e733040067d88358b4da0e9233b5b995044c31a  v1.54h.zip
```

That's the sha512s I am getting after downloading the zips from each source

**Comment by IAHM-COL** [comment]
After unzipping, I run the diff, for evaluating what's different. FYI `ImageJ-1.54h` is after unzipping the github, while `source` is after unzipping the NIH 

```
~/test $ diff ImageJ-1.54h source
Only in ImageJ-1.54h: applet.html
Only in source: aREADME.txt
Only in source: build2.xml
Only in source: build copy.xml
diff ImageJ-1.54h/build.xml source/build.xml
29a30
>     <copy file="functions.html" todir="${build.dir}" />
Only in ImageJ-1.54h: compile.bat
Only in ImageJ-1.54h: .github
Only in ImageJ-1.54h: .gitignore
Common subdirectories: ImageJ-1.54h/ij and source/ij
Common subdirectories: ImageJ-1.54h/images and source/images
Only in ImageJ-1.54h: LICENSE.txt
Common subdirectories: ImageJ-1.54h/macros and source/macros
Only in ImageJ-1.54h: .mailmap
Only in ImageJ-1.54h: nbproject
Common subdirectories: ImageJ-1.54h/plugins and source/plugins
Only in ImageJ-1.54h: policy
Only in ImageJ-1.54h: pom.xml
Only in ImageJ-1.54h: README.md
diff ImageJ-1.54h/release-notes.html source/release-notes.html
8c8
< <li> <u>1.54h  15 December 2023</u>
---
> <li> <u>1.54h  14 December 2023</u>
11c11
< the RGB to indexed color conversion done by the
---
> the RGB to indexed color conversion done by
20,21c20,21
< and Dialog.getYesNoCancel macro functions
< (<a href="http://wsr.imagej.net/macros/YesNoCancelDialog.ijm">example</a>).
---
> and Dialog.getYesNoCancel macro functions DOCUMENT
> (<a href="http://wsr.imagej.net/macros/YesNoCancelDialog.ijm">example</a>,
28c28
< function not working in batch mode.
---
> functio not working in batch mode.
30c30
< "Composite" mode images.
---
> COMPOSITE mode images.
Only in ImageJ-1.54h: run_appletviewer.bat
Only in ImageJ-1.54h: tests
```

**Comment by AndrewAmmerlaan** [comment]
> `Only in ImageJ-1.54h: tests`

I think we can stick to one version, let's use this one that has the tests.

**Comment by IAHM-COL** [comment]
> > `Only in ImageJ-1.54h: tests`
> 
> I think we can stick to one version, let's use this one that has the tests.

I am ok with your call here. Let me update this pull request maintaining only the github sources.

**Comment by IAHM-COL** [comment]
> > >  Let me update this pull request maintaining only the github sources.

bf5e74c0442698cf7feb2cddccd1d57eca91612c

**Comment by AndrewAmmerlaan** [comment]
Thanks :+1:

**Comment by IAHM-COL** [comment]
:+1:

**Pull request closed without merging**
