### PR TITLE
Enable python 3.6 support for dev-python/snakemake

### PR DESCRIPTION
**Pull request by mschilli87**
Tested locally without any issues.

### CODE REVIEW

**Comment by mschilli87** [comment]
Is there anything I can do to get this merged? Did I do something wrong?

**Comment by TheChymera** [comment]
Hello @mschilli87 , sorry for the lack of responsiveness, the overlay maintainer team is a collection of people from different fields specializing on and mainly concerned with specific package subsets, so if none of us is in your field and using your specific package, it takes a long time for someone to get to it.

One way to solve this issue is for more non-maintainer contributors to contribute regularly, and establish enough trust for us to make them maintainers with push access. If you have the time, you could go through others' PRs, test them, and ping someone, e.g. me.

Getting back to your PR, it looks good to me, but given the time which has passed, you should update the copyright line, and scratch 3_4 from the python compatibility list. Also, you might want to test with 3_7 as well.

**Comment by heroxbd** [comment]
@mschilli87 would you please update the ebuild as requested by the reviewer?

**Comment by mschilli87** [comment]
@heroxbd: Yes, it's on my list. Sorry for taking so long. I'll get to it 'soon'. :wink:

**Comment by mschilli87** [comment]
@heroxbd: Sorry for taking so long. As you can see, I'm not any better than the maintainers either, :wink:

**Comment by TheChymera** [comment]
@mschilli87 I know this is annoying (since I've been in your exact position many times) but as time passes so do the requirements for Python. Could you please scrap 3_5 (it is being dropped), but test 3_7 as well. The main tree is stabilizing it, and we should have it preset on all packages that support it. 

Also, it appears this version is rather ancient. Could you maybe submit the changes I mentioned above along with a version bump to [the current version](https://github.com/snakemake/snakemake/releases).

**Comment by mschilli87** [comment]
@TheChymera: I'm sorry but I don't have 3_7 on my system and with the 2_7 purge ongoing I don't have time to set it up. I can remove 3_5 (though doing so would take any maintainer less time than asking me to do so).

Also I'd be happy to bump the version in a separate PR but right now I'm concerned to get any version to work on my system (*i.e* 3_6). I did so using a local overlay in which I'm using the ebuild I submitted here.
I simply felt like sharing those changes with the community as they were trivial but might pose a challenge to Gentoo newbies.

I'll bump the version once I have time and get it to work. There are also dependencies to consider. When I wrote this datrie had no 3_7 and AFAICT has no 3_8 support as of now.
So this could be more work and if I do it I want to be sure it works.
I know this ebuild works on 3_6 and I use it. If you take it, I'll happily share a 3_7 and/or version bump once I get to it. If not, feel free to keep the ancient version for 3_5 around or drop the package (which might be more honest to the users if nobody maintains it).

**Comment by heroxbd** [comment]
@mschilli87  I am okay with a Python 3.6 ebuild if testing out Python 3.7 poses too much work to you.

**Comment by mschilli87** [comment]
@heroxbd: I went ahead and installed 3_7 next to 3_6. I'll try to test it as soon as I have time but no promises. :wink:

I'd still prefer this to be merged (unless it is really not considered an improvement at  this point) and open a new PR adding to 3_7 and maybe later one bumping the version.

This here works on my system since 2018 any anobody needing snakemake has to keep 3_5 around for it so far.

**Comment by heroxbd** [comment]
Thank you @mschilli87 for the PR!

**Pull request closed without merging**
