### PR TITLE
sci-physics/genfit: Add functional live ebuild.

### PR DESCRIPTION
**Pull request by olifre**
This also fixes documentation generation
and installation.

Package-Manager: Portage-3.0.12, Repoman-3.0.2
Signed-off-by: Oliver Freyermuth <o.freyermuth@googlemail.com>

### CODE REVIEW

**Comment by olifre** [comment]
As mentioned in #1021 , documentation generation can not be done with the `docs` eclass, since CMake is used by the package to replace some macros in the `Doxyfile.in`, so I changed back to the `cmake`-based documentation generation. 

Upstream is sadly not doing releases:
https://github.com/GenFit/GenFit/issues/42
and the last tagged `02.00.00` package which is currently in this overlay does not work with any unmasked ROOT version in Gentoo portage anymore. 

I am not sure what is the best way to proceed — we could package a date-based tag to have a kind of release? 
Dropping the old `02.00.00` version which is not of much use anymore could be done afterwards.

**Comment by AndrewAmmerlaan** [comment]
> I am not sure what is the best way to proceed — we could package a date-based tag to have a kind of release?
> Dropping the old `02.00.00` version which is not of much use anymore could be done afterwards.

This seems like a good idea to me, we could just add a 02.00.00_p20201231.ebuild and remove the old 02.00.00 version :+1:

**Comment by olifre** [comment]
> This seems like a good idea to me, we could just add a 02.00.00_p20201231.ebuild and remove the old 02.00.00 version :+1:

Thanks! 
I've done exactly that in the linked commits. One note:

I also force-pushed the `9999` version again, removing all references in there to the old, pre-GitHub tag (so we get rid of the HTTP warnings by `repoman`). I've used `EGIT_COMMIT=""` in the unused code branch there, so when making a new tagged version, one can copy the `9999` ebuild over and fill in the `EGIT_COMMIT`. 

I have not added myself as maintaner (not sure if I should). I have a look at `genfit` from time to time, but am not actively using it anymore, so I can for sure help out from time to time, but it will not be my highest priority. If I should still add myself, just let me know.

**Comment by TheChymera** [comment]
> 02.00.00_p20201231
Yes, that's generally the way to go if upstream does not version.

> I have not added myself as maintaner (not sure if I should).
If the package does not already have another maintainer, it means whatever attention level you're willing to prioritize it at is higher than what anybody else is willing to give it :) It also helps other maintainers to reach out to you if they have issues understanding the ebuild.

Please add yourself as a maintainer, and merge that into the version bump commit. Just for the sake of consistency and grep-ability, a commit text like `version bump 02.00.00_p20201231 snapshot` would be better :)

**Comment by olifre** [comment]
> Please add yourself as a maintainer, and merge that into the version bump commit. 

Done, I merged that in the first commit adding the live `ebuild`. 

> Just for the sake of consistency and grep-ability, a commit text like `version bump 02.00.00_p20201231 snapshot` would be better :)

Indeed, that seems much more useful, I completely missed that since I did not consider it a "bump", but of course it is :wink:.

**Comment by TheChymera** [comment]
closed by https://gitweb.gentoo.org/proj/sci.git/commit/?id=1f55f85dcb465ea7267a5362ac4ab3b5fc319c63 and preceding.

**Pull request closed without merging**
