### PR TITLE
eclass/intel-sdp-r1: fix for the MPI wrapper scripts

### PR DESCRIPTION
**Pull request by abusse**
All MPI wrapper scripts were not working as the I_MPI_SUBSTITUTE_INSTALLDIR string was not replaced by the actual root dir. This commits adds a substitution for I_MPI_SUBSTITUTE_INSTALLDIR trough sed.

### CODE REVIEW

**Comment by TheChymera** [comment]
Hi @abusse , sorry for the long hiatus. The overlay has suffered from very low manpower over the last 2-3 years. We're currently bringing it up to scratch again. Is this PR still relevant in light of recent updates?

**Comment by abusse** [comment]
I wasn't able to determine whether it is still valid with a quick check. I will look into it in more detail as soon as I find some time to spare.

**Comment by TheChymera** [comment]
@abusse no worries, leaving this open for now :)

**Comment by abusse** [comment]
So I did some digging and as a result a created a version bump for the ICC and libraries in #1040. However, Intel seems no longer to include MPI libraries, making this patch obsolete for current packages. However, if someone still has the old ones (which I do not have access to any longer) this patch might still be helpful

**Comment by epsilon-0** [comment]
Intel MPI - https://github.com/gentoo/gentoo/pull/18452

**Pull request closed without merging**
