### PR TITLE
Dev-python/matplotlib2tikz remove duplicate

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
Package has been renamed

also updated the ebuild to new version
updated to EAPI 7
added support for running the tests
added support for building the docs
bumped the python targets (and tested against them)
introduced new dependency dev-python/exdown

PR to ::gentoo bumping 0.9.2 to 0.9.4 will follow once this has been approved and merged

### CODE REVIEW

**Comment by epsilon-0** [comment]
Why is this being put in ::science, if the package already exists in ::gentoo?
We are actively removing duplicates.
I suggest adding the live versions to ::gentoo as well.

**Comment by AndrewAmmerlaan** [comment]
Aah, I was not aware that duplicates were being removed, I simply noticed this package lying around and remember bumping and moving it before in ::gentoo so I figured I'd move it here too.

I'll rebase this PR to remove the duplicate package, and make a new PR to ::gentoo for this

**Comment by AndrewAmmerlaan** [comment]
Alright done, this PR now removes the duplicate

And this PR bumps the ::gentoo package: https://github.com/gentoo/gentoo/pull/17773

**Comment by epsilon-0** [comment]
Thanks a lot, will merge tonight.

**Comment by epsilon-0** [comment]
I've merged it in a3551c58103b730d73974dfd0d8d48a1916f8887

**Comment by AndrewAmmerlaan** [comment]
> I've merged it in [a3551c5](https://github.com/gentoo/sci/commit/a3551c58103b730d73974dfd0d8d48a1916f8887)

Awesome, Thanks :smile:

**Pull request closed without merging**
