### PR TITLE
sys-kernel/dkms: dynamic kernel module support

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
Package-Manager: Portage-3.0.12, Repoman-3.0.2
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@riseup.net>

### CODE REVIEW

**Comment by epsilon-0** [comment]
OK, this is looking good.
I'm not going to be able to merge right now cuz my build server got "semi-borked" but I'll look at the other PRs.

**Comment by epsilon-0** [comment]
Hmm, after sleeping on it I had a thought. Maybe there should be a kernel config check that module loading and unloading support is enabled?

**Comment by AndrewAmmerlaan** [comment]
> Hmm, after sleeping on it I had a thought. Maybe there should be a kernel config check that module loading and unloading support is enabled

Good idea! On it

**Comment by AndrewAmmerlaan** [comment]
> Hmm, after sleeping on it I had a thought. Maybe there should be a kernel config check that module loading and unloading support is enabled?

Fixed, this now checks for CONFIG_MODULES, which should be sufficient for this package I think.

**Comment by epsilon-0** [comment]
This killed the build because it could not find the .config in the chroot :open_mouth:
We want a warning not a kill, to do a warning you should do `CONFIG_CHECK="~MODULES"`, the `~` makes it non fatal.

**Comment by AndrewAmmerlaan** [comment]
> This killed the build because it could not find the .config in the chroot open_mouth
> We want a warning not a kill, to do a warning you should do `CONFIG_CHECK="~MODULES"`, the `~` makes it non fatal.

Fixed, after reading the modules article on the Gentoo wiki I also added: `RDEPEND="sys-apps/kmod"`.

**Pull request closed without merging**
